#!/usr/bin/env bash
set -euo pipefail

sudo apt-get update
sudo apt-get install -y postgresql-client curl zip unzip jq

PGHOST="${POSTGRES_HOST:-localhost}"
PGPORT="${POSTGRES_PORT:-5432}"
PGDATABASE="${POSTGRES_DB:-project-sem-1}"
PGUSER="${POSTGRES_USER:-validator}"
PGPASSWORD="${POSTGRES_PASSWORD:-val1dat0r}"
export PGPASSWORD

# ждём Postgres
for i in {1..40}; do
  if psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c '\q' >/dev/null 2>&1; then
    break
  fi
  sleep 0.5
done

# Таблица под tests.sh + автоинкрементный id
psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" <<'SQL'
CREATE TABLE IF NOT EXISTS prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  category TEXT,
  price DOUBLE PRECISION,
  create_date DATE
);

-- на случай если таблица была создана раньше без IDENTITY:
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name='prices' AND column_name='id'
      AND identity_generation IS NULL
  ) THEN
    EXECUTE 'ALTER TABLE prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END$$;
SQL

go mod tidy
